#!/usr/bin/env bash
# manage script

if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "start" ]]; then
        # Start the process
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [[ "$1" == "stop" ]]; then
        # Stop the process
        if [[ -f /var/run/my_process.pid ]]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "No process found to stop."
        fi
    elif [[ "$1" == "restart" ]]; then
        # Restart the process
        if [[ -f /var/run/my_process.pid ]]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi
        # Start the process again
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"  # Only print restart message
    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

